`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module EXU(
  input  [31:0] io_a,
                io_b,
  input         io_add,
                io_lh20,
                io_sub,
                io_slt,
                io_sltu,
                io_xor,
                io_or,
                io_and,
                io_sll,
                io_srl,
                io_sra,
                io_mul,
                io_mulh,
                io_mulsu,
                io_mulu,
                io_div,
                io_divu,
                io_rem,
                io_remu,
  output [31:0] io_result
);

  wire [31:0] _io_result_T_3 = io_a + io_b;
  wire [62:0] _io_result_T_27 = {31'h0, io_a} << io_b[4:0];
  wire [31:0] _GEN = {27'h0, io_b[4:0]};
  wire [63:0] _GEN_0 = {{32{io_a[31]}}, io_a};
  wire [63:0] _io_result_T_36 = _GEN_0 * {{32{io_b[31]}}, io_b};
  wire [63:0] _GEN_1 = {32'h0, io_b};
  wire [63:0] _io_result_T_41 = _GEN_0 * _GEN_1;
  wire [63:0] _io_result_T_48 = {32'h0, io_a} * _GEN_1;
  wire [32:0] _io_result_T_51 = $signed({io_a[31], io_a}) / $signed({io_b[31], io_b});
  assign io_result =
    io_add
      ? _io_result_T_3
      : io_lh20
          ? io_b
          : io_sub
              ? io_a - io_b
              : io_slt
                  ? {31'h0, $signed(io_a) < $signed(io_b)}
                  : io_sltu
                      ? {31'h0, io_a < io_b}
                      : io_xor
                          ? io_a ^ io_b
                          : io_or
                              ? io_a | io_b
                              : io_and
                                  ? io_a & io_b
                                  : io_sll
                                      ? _io_result_T_27[31:0]
                                      : io_srl
                                          ? io_a >> _GEN
                                          : io_sra
                                              ? $signed($signed(io_a) >>> _GEN)
                                              : io_mul
                                                  ? _io_result_T_36[31:0]
                                                  : io_mulh
                                                      ? _io_result_T_36[63:32]
                                                      : io_mulsu
                                                          ? _io_result_T_41[63:32]
                                                          : io_mulu
                                                              ? _io_result_T_48[63:32]
                                                              : io_div
                                                                  ? _io_result_T_51[31:0]
                                                                  : io_divu
                                                                      ? io_a / io_b
                                                                      : io_rem
                                                                          ? $signed(io_a)
                                                                            % $signed(io_b)
                                                                          : io_remu
                                                                              ? io_a
                                                                                % io_b
                                                                              : _io_result_T_3;
endmodule

