`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module IDU(
  input  [31:0] io_inst,
                io_pc,
                io_rs1data,
                io_rs2data,
  output        io_jalr,
                io_ecall,
                io_mret,
                io_dobranch,
                io_I,
                io_S,
                io_U,
                io_J,
                io_R,
  output [4:0]  io_rs1addr,
                io_rs2addr,
                io_rdaddr,
  output        io_alu_add,
                io_alu_lh20,
                io_alu_sub,
                io_alu_slt,
                io_alu_sltu,
                io_alu_xor,
                io_alu_or,
                io_alu_and,
                io_alu_sll,
                io_alu_srl,
                io_alu_sra,
                io_alu_mul,
                io_alu_mulh,
                io_alu_mulsu,
                io_alu_mulu,
                io_alu_div,
                io_alu_divu,
                io_alu_rem,
                io_alu_remu,
  output [31:0] io_alu_a,
                io_alu_b,
  output        io_mem_load,
                io_csr,
                io_csr_write,
                io_csr_set,
                io_csr_clear,
  output [11:0] io_csraddr
);

  wire       isLoad = io_inst[6:0] == 7'h3;
  wire       isStore = io_inst[6:0] == 7'h23;
  wire       isBranch = io_inst[6:0] == 7'h63;
  wire       isJalr = io_inst[6:0] == 7'h67;
  wire       isJal = io_inst[6:0] == 7'h6F;
  wire       isOpImm = io_inst[6:0] == 7'h13;
  wire       isRop = io_inst[6:0] == 7'h33;
  wire       isCsr = io_inst[6:0] == 7'h73;
  wire       _io_alu_b_T_1 = io_inst[14:12] == 3'h1;
  wire       _isMulsu_T_1 = io_inst[14:12] == 3'h2;
  wire       _isMulu_T_1 = io_inst[14:12] == 3'h3;
  wire       isAuipc = io_inst[6:0] == 7'h17;
  wire       _isSrl_T = io_inst[31:25] == 7'h0;
  wire       _isSra_T = io_inst[31:25] == 7'h20;
  wire       _isSra_T_3 = isOpImm | isRop;
  wire       _isDiv_T_1 = io_inst[14:12] == 3'h4;
  wire       _isRem_T_1 = io_inst[14:12] == 3'h6;
  wire       _io_alu_b_T = io_inst[14:12] == 3'h5;
  wire       _isRemu_T = io_inst[31:25] == 7'h1;
  wire       io_I_0 = isLoad | isJalr | isOpImm;
  wire       io_U_0 = io_inst[6:0] == 7'h37 | isAuipc;
  wire       _io_dobranch_T_11 = ~(|(io_inst[14:12])) & io_rs1data == io_rs2data;
  wire [7:0] _GEN =
    {{io_rs1data >= io_rs2data},
     {io_rs1data < io_rs2data},
     {$signed(io_rs1data) >= $signed(io_rs2data)},
     {$signed(io_rs1data) < $signed(io_rs2data)},
     {_io_dobranch_T_11},
     {_io_dobranch_T_11},
     {io_rs1data != io_rs2data},
     {_io_dobranch_T_11}};
  wire [4:0] _Imm_T = {io_I_0, isStore, isBranch, io_U_0, isJal};
  assign io_jalr = isJalr;
  assign io_ecall = io_inst == 32'h73;
  assign io_mret = io_inst == 32'h30200073;
  assign io_dobranch = isBranch & _GEN[io_inst[14:12]];
  assign io_I = io_I_0;
  assign io_S = isStore;
  assign io_U = io_U_0;
  assign io_J = isJal;
  assign io_R = isRop;
  assign io_rs1addr = io_inst[19:15];
  assign io_rs2addr = io_inst[24:20];
  assign io_rdaddr = io_inst[11:7];
  assign io_alu_add =
    isRop & ~(|(io_inst[14:12])) & _isSrl_T | isOpImm & ~(|(io_inst[14:12])) | isLoad
    | isStore | isJalr | isBranch | isAuipc | isJal;
  assign io_alu_lh20 = io_U_0;
  assign io_alu_sub = isRop & ~(|(io_inst[14:12])) & _isSra_T;
  assign io_alu_slt = _isSra_T_3 & _isMulsu_T_1;
  assign io_alu_sltu = _isSra_T_3 & _isMulu_T_1;
  assign io_alu_xor = _isDiv_T_1 & (isRop | isOpImm);
  assign io_alu_or = _isRem_T_1 & _isSra_T_3;
  assign io_alu_and = (&(io_inst[14:12])) & _isSra_T_3;
  assign io_alu_sll = _io_alu_b_T_1 & _isSra_T_3;
  assign io_alu_srl = _isSrl_T & _io_alu_b_T & _isSra_T_3;
  assign io_alu_sra = _isSra_T & _io_alu_b_T & _isSra_T_3;
  assign io_alu_mul = _isRemu_T & ~(|(io_inst[14:12])) & isRop;
  assign io_alu_mulh = _isRemu_T & _io_alu_b_T_1 & isRop;
  assign io_alu_mulsu = _isRemu_T & _isMulsu_T_1 & isRop;
  assign io_alu_mulu = _isRemu_T & _isMulu_T_1 & isRop;
  assign io_alu_div = _isRemu_T & _isDiv_T_1 & isRop;
  assign io_alu_divu = _isRemu_T & _io_alu_b_T & isRop;
  assign io_alu_rem = _isRemu_T & _isRem_T_1 & isRop;
  assign io_alu_remu = _isRemu_T & (&(io_inst[14:12])) & isRop;
  assign io_alu_a = isAuipc | isJal | isBranch ? io_pc : io_rs1data;
  assign io_alu_b =
    isRop | isRop & (_io_alu_b_T | _io_alu_b_T_1)
      ? io_rs2data
      : _Imm_T == 5'h1
          ? {{12{io_inst[31]}}, io_inst[19:12], io_inst[20], io_inst[30:21], 1'h0}
          : _Imm_T == 5'h2
              ? {io_inst[31:12], 12'h0}
              : _Imm_T == 5'h4
                  ? {{21{io_inst[31]}}, io_inst[30:25], io_inst[11:8], 1'h0}
                  : _Imm_T == 5'h8
                      ? {{20{io_inst[31]}}, io_inst[31:25], io_inst[11:7]}
                      : _Imm_T == 5'h10 ? {{20{io_inst[31]}}, io_inst[31:20]} : 32'h0;
  assign io_mem_load = isLoad;
  assign io_csr = isCsr;
  assign io_csr_write = isCsr & _io_alu_b_T_1;
  assign io_csr_set = isCsr & _isMulsu_T_1;
  assign io_csr_clear = isCsr & _isMulu_T_1;
  assign io_csraddr = io_inst[31:20];
endmodule

