`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module LSU(
  input  [31:0] io_exu_result,
  input  [2:0]  io_funct3,
                io_load_funct3,
  input  [31:0] io_load_addr,
                io_gpr_rs2data,
  output [31:0] io_lsu_addr,
                io_lsu_wdata,
  output [7:0]  io_lsu_wmask,
  output [31:0] io_lsu_loaddata,
  input  [31:0] io_lsu_rdata
);

  wire [3:0][7:0]  _GEN =
    {{io_lsu_rdata[31:24]},
     {io_lsu_rdata[23:16]},
     {io_lsu_rdata[15:8]},
     {io_lsu_rdata[7:0]}};
  wire [7:0]       selected_byte = _GEN[io_load_addr[1:0]];
  wire [15:0]      selected_halfword =
    io_load_addr[1] ? io_lsu_rdata[31:16] : io_lsu_rdata[15:0];
  wire [7:0][31:0] _GEN_0 =
    {{32'h0},
     {32'h0},
     {{16'h0, selected_halfword}},
     {{24'h0, selected_byte}},
     {32'h0},
     {io_lsu_rdata},
     {{{16{selected_halfword[15]}}, selected_halfword}},
     {{{24{selected_byte[7]}}, selected_byte}}};
  wire             _base_mask_T_1 = io_funct3 == 3'h0;
  wire             _base_mask_T_2 = io_funct3 == 3'h1;
  wire             _base_mask_T_4 = io_funct3 == 3'h2;
  wire [31:0]      base_data =
    _base_mask_T_4
      ? io_gpr_rs2data
      : _base_mask_T_2
          ? {16'h0, io_gpr_rs2data[15:0]}
          : _base_mask_T_1 ? {24'h0, io_gpr_rs2data[7:0]} : 32'h0;
  wire [31:0]      _GEN_1 = {base_data[15:0], 16'h0};
  wire [3:0][31:0] _GEN_2 =
    {{{base_data[7:0], 24'h0}}, {_GEN_1}, {{base_data[23:0], 8'h0}}, {base_data}};
  assign io_lsu_addr = io_exu_result;
  assign io_lsu_wdata =
    _base_mask_T_4
      ? io_gpr_rs2data
      : _base_mask_T_2
          ? (io_exu_result[1] ? _GEN_1 : base_data)
          : _base_mask_T_1 ? _GEN_2[io_exu_result[1:0]] : 32'h0;
  assign io_lsu_wmask =
    {1'h0,
     {3'h0,
      _base_mask_T_4 ? 4'hF : {2'h0, _base_mask_T_2 ? 2'h3 : {1'h0, _base_mask_T_1}}}
       << io_exu_result[1:0]};
  assign io_lsu_loaddata = _GEN_0[io_load_funct3];
endmodule

