`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module SZCOREtop(
  input         io_cpu_clk,
                io_cpu_rst,
  output        io_ifetch_req,
  output [31:0] io_ifetch_addr,
  input         io_ifetch_valid,
  input  [31:0] io_ifetch_inst,
  output [3:0]  io_daccess_ren,
  output [31:0] io_daccess_addr,
  input         io_daccess_rvalid,
  input  [31:0] io_daccess_rdata,
  output [3:0]  io_daccess_wen,
  output [31:0] io_daccess_wdata,
  input         io_daccess_wresp,
  output [31:0] io_inst,
                io_pc
);

  wire [31:0] _csr_io_readval;
  wire [31:0] _gpr_io_rs1data;
  wire [31:0] _gpr_io_rs2data;
  wire [31:0] _wbu_io_writeback_data;
  wire [31:0] _lsu_io_lsu_addr;
  wire [31:0] _lsu_io_lsu_wdata;
  wire [7:0]  _lsu_io_lsu_wmask;
  wire [31:0] _lsu_io_lsu_loaddata;
  wire [31:0] _exu_io_result;
  wire        _idu_io_jalr;
  wire        _idu_io_ecall;
  wire        _idu_io_mret;
  wire        _idu_io_dobranch;
  wire        _idu_io_I;
  wire        _idu_io_S;
  wire        _idu_io_U;
  wire        _idu_io_J;
  wire        _idu_io_R;
  wire [4:0]  _idu_io_rs1addr;
  wire [4:0]  _idu_io_rs2addr;
  wire [4:0]  _idu_io_rdaddr;
  wire        _idu_io_alu_add;
  wire        _idu_io_alu_lh20;
  wire        _idu_io_alu_sub;
  wire        _idu_io_alu_slt;
  wire        _idu_io_alu_sltu;
  wire        _idu_io_alu_xor;
  wire        _idu_io_alu_or;
  wire        _idu_io_alu_and;
  wire        _idu_io_alu_sll;
  wire        _idu_io_alu_srl;
  wire        _idu_io_alu_sra;
  wire        _idu_io_alu_mul;
  wire        _idu_io_alu_mulh;
  wire        _idu_io_alu_mulsu;
  wire        _idu_io_alu_mulu;
  wire        _idu_io_alu_div;
  wire        _idu_io_alu_divu;
  wire        _idu_io_alu_rem;
  wire        _idu_io_alu_remu;
  wire [31:0] _idu_io_alu_a;
  wire [31:0] _idu_io_alu_b;
  wire        _idu_io_mem_load;
  wire        _idu_io_csr;
  wire        _idu_io_csr_write;
  wire        _idu_io_csr_set;
  wire        _idu_io_csr_clear;
  wire [11:0] _idu_io_csraddr;
  wire [31:0] _ifu_io_inst;
  wire [31:0] _ifu_io_pc;
  reg         fetchOutstanding;
  reg         memPending;
  reg         memIsLoad;
  reg  [4:0]  memRd;
  reg  [2:0]  memFunct3;
  reg  [31:0] memAddr;
  reg  [3:0]  daccessRenReg;
  reg  [31:0] daccessAddrReg;
  reg  [3:0]  daccessWenReg;
  reg  [31:0] daccessWdataReg;
  wire        fetchAccept = io_ifetch_valid & fetchOutstanding;
  wire        isMemAccess = _idu_io_mem_load | _idu_io_S;
  wire        memDone = memPending & (memIsLoad ? io_daccess_rvalid : io_daccess_wresp);
  wire        io_ifetch_req_0 =
    ~io_cpu_rst & ~fetchOutstanding & ~memPending & ~io_ifetch_valid;
  wire        _gpr_io_rddata_T = memDone & memIsLoad;
  wire        _csr_io_write_T = _idu_io_csr_write & fetchAccept;
  always @(posedge io_cpu_clk) begin
    if (io_cpu_rst) begin
      fetchOutstanding <= 1'h0;
      memPending <= 1'h0;
      memIsLoad <= 1'h0;
      memRd <= 5'h0;
      memFunct3 <= 3'h0;
      memAddr <= 32'h0;
      daccessRenReg <= 4'h0;
      daccessAddrReg <= 32'h0;
      daccessWenReg <= 4'h0;
      daccessWdataReg <= 32'h0;
    end
    else begin
      automatic logic issueMemoryAccess = fetchAccept & isMemAccess;
      fetchOutstanding <= ~fetchAccept & (io_ifetch_req_0 | fetchOutstanding);
      memPending <= ~memDone & (issueMemoryAccess | memPending);
      if (issueMemoryAccess) begin
        memIsLoad <= _idu_io_mem_load;
        memRd <= _idu_io_rdaddr;
        memFunct3 <= _ifu_io_inst[14:12];
        memAddr <= _lsu_io_lsu_addr;
        daccessAddrReg <= _lsu_io_lsu_addr;
        daccessWdataReg <= _lsu_io_lsu_wdata;
      end
      daccessRenReg <=
        issueMemoryAccess & _idu_io_mem_load ? _lsu_io_lsu_wmask[3:0] : 4'h0;
      daccessWenReg <= issueMemoryAccess & _idu_io_S ? _lsu_io_lsu_wmask[3:0] : 4'h0;
    end
  end // always @(posedge)
  IFU ifu (
    .clock         (io_cpu_clk),
    .reset         (io_cpu_rst),
    .io_fetch      (fetchAccept & ~isMemAccess | memDone),
    .io_jump
      (_idu_io_dobranch | _idu_io_J | _idu_io_jalr | _idu_io_ecall | _idu_io_mret),
    .io_jumpTarget (_idu_io_mret ? _csr_io_readval : _exu_io_result),
    .io_ifu_raddr  (io_ifetch_addr),
    .io_ifu_rdata  (io_ifetch_inst),
    .io_inst       (_ifu_io_inst),
    .io_pc         (_ifu_io_pc)
  );
  IDU idu (
    .io_inst      (fetchAccept ? _ifu_io_inst : 32'h13),
    .io_pc        (_ifu_io_pc),
    .io_rs1data   (_gpr_io_rs1data),
    .io_rs2data   (_gpr_io_rs2data),
    .io_jalr      (_idu_io_jalr),
    .io_ecall     (_idu_io_ecall),
    .io_mret      (_idu_io_mret),
    .io_dobranch  (_idu_io_dobranch),
    .io_I         (_idu_io_I),
    .io_S         (_idu_io_S),
    .io_U         (_idu_io_U),
    .io_J         (_idu_io_J),
    .io_R         (_idu_io_R),
    .io_rs1addr   (_idu_io_rs1addr),
    .io_rs2addr   (_idu_io_rs2addr),
    .io_rdaddr    (_idu_io_rdaddr),
    .io_alu_add   (_idu_io_alu_add),
    .io_alu_lh20  (_idu_io_alu_lh20),
    .io_alu_sub   (_idu_io_alu_sub),
    .io_alu_slt   (_idu_io_alu_slt),
    .io_alu_sltu  (_idu_io_alu_sltu),
    .io_alu_xor   (_idu_io_alu_xor),
    .io_alu_or    (_idu_io_alu_or),
    .io_alu_and   (_idu_io_alu_and),
    .io_alu_sll   (_idu_io_alu_sll),
    .io_alu_srl   (_idu_io_alu_srl),
    .io_alu_sra   (_idu_io_alu_sra),
    .io_alu_mul   (_idu_io_alu_mul),
    .io_alu_mulh  (_idu_io_alu_mulh),
    .io_alu_mulsu (_idu_io_alu_mulsu),
    .io_alu_mulu  (_idu_io_alu_mulu),
    .io_alu_div   (_idu_io_alu_div),
    .io_alu_divu  (_idu_io_alu_divu),
    .io_alu_rem   (_idu_io_alu_rem),
    .io_alu_remu  (_idu_io_alu_remu),
    .io_alu_a     (_idu_io_alu_a),
    .io_alu_b     (_idu_io_alu_b),
    .io_mem_load  (_idu_io_mem_load),
    .io_csr       (_idu_io_csr),
    .io_csr_write (_idu_io_csr_write),
    .io_csr_set   (_idu_io_csr_set),
    .io_csr_clear (_idu_io_csr_clear),
    .io_csraddr   (_idu_io_csraddr)
  );
  EXU exu (
    .io_a      (_idu_io_alu_a),
    .io_b      (_idu_io_alu_b),
    .io_add    (_idu_io_alu_add),
    .io_lh20   (_idu_io_alu_lh20),
    .io_sub    (_idu_io_alu_sub),
    .io_slt    (_idu_io_alu_slt),
    .io_sltu   (_idu_io_alu_sltu),
    .io_xor    (_idu_io_alu_xor),
    .io_or     (_idu_io_alu_or),
    .io_and    (_idu_io_alu_and),
    .io_sll    (_idu_io_alu_sll),
    .io_srl    (_idu_io_alu_srl),
    .io_sra    (_idu_io_alu_sra),
    .io_mul    (_idu_io_alu_mul),
    .io_mulh   (_idu_io_alu_mulh),
    .io_mulsu  (_idu_io_alu_mulsu),
    .io_mulu   (_idu_io_alu_mulu),
    .io_div    (_idu_io_alu_div),
    .io_divu   (_idu_io_alu_divu),
    .io_rem    (_idu_io_alu_rem),
    .io_remu   (_idu_io_alu_remu),
    .io_result (_exu_io_result)
  );
  LSU lsu (
    .io_exu_result   (_exu_io_result),
    .io_funct3       (_ifu_io_inst[14:12]),
    .io_load_funct3  (memPending ? memFunct3 : _ifu_io_inst[14:12]),
    .io_load_addr    (memPending ? memAddr : _lsu_io_lsu_addr),
    .io_gpr_rs2data  (_gpr_io_rs2data),
    .io_lsu_addr     (_lsu_io_lsu_addr),
    .io_lsu_wdata    (_lsu_io_lsu_wdata),
    .io_lsu_wmask    (_lsu_io_lsu_wmask),
    .io_lsu_loaddata (_lsu_io_lsu_loaddata),
    .io_lsu_rdata    (io_daccess_rdata)
  );
  WBU wbu (
    .io_exuresult      (_exu_io_result),
    .io_mem_rdata      (_lsu_io_lsu_loaddata),
    .io_pc             (_ifu_io_pc),
    .io_mem_load       (_idu_io_mem_load),
    .io_J              (_idu_io_J),
    .io_jalr           (_idu_io_jalr),
    .io_csr            (_idu_io_csr),
    .io_csrval         (_csr_io_readval),
    .io_writeback_data (_wbu_io_writeback_data)
  );
  GPR gpr (
    .clock      (io_cpu_clk),
    .reset      (io_cpu_rst),
    .io_rs1addr (_idu_io_rs1addr),
    .io_rs2addr (_idu_io_rs2addr),
    .io_rdaddr  (_gpr_io_rddata_T ? memRd : _idu_io_rdaddr),
    .io_rs1data (_gpr_io_rs1data),
    .io_rs2data (_gpr_io_rs2data),
    .io_rddata  (_gpr_io_rddata_T ? _lsu_io_lsu_loaddata : _wbu_io_writeback_data),
    .io_we
      (fetchAccept & ~isMemAccess & ~_idu_io_S
       & (_idu_io_R | _idu_io_I | _idu_io_U | _idu_io_J | _idu_io_mem_load | _idu_io_csr)
       | _gpr_io_rddata_T)
  );
  CSR csr (
    .clock      (io_cpu_clk),
    .reset      (io_cpu_rst),
    .io_addr    (_idu_io_csraddr),
    .io_op_val  (_gpr_io_rs1data),
    .io_write   (_csr_io_write_T & ~isMemAccess),
    .io_set     (_idu_io_csr_set),
    .io_ecall   (_idu_io_ecall & fetchAccept & ~isMemAccess),
    .io_mret    (_idu_io_mret & fetchAccept & ~isMemAccess),
    .io_clear   (_idu_io_csr_clear),
    .io_pc      (_ifu_io_pc),
    .io_we      (_csr_io_write_T & ~isMemAccess),
    .io_readval (_csr_io_readval)
  );
  assign io_ifetch_req = io_ifetch_req_0;
  assign io_daccess_ren = daccessRenReg;
  assign io_daccess_addr = daccessAddrReg;
  assign io_daccess_wen = daccessWenReg;
  assign io_daccess_wdata = daccessWdataReg;
  assign io_inst = _ifu_io_inst;
  assign io_pc = _ifu_io_pc;
endmodule

