`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module cpu_core(
  input         cpu_rst,
                cpu_clk,
  output        ifetch_req /* verilator public */,
  output [31:0] ifetch_addr /* verilator public */,
  input         ifetch_valid /* verilator public */,
  input  [31:0] ifetch_inst,
  output [3:0]  daccess_ren,
  output [31:0] daccess_addr,
  input         daccess_rvalid,
  input  [31:0] daccess_rdata,
  output [3:0]  daccess_wen,
  output [31:0] daccess_wdata,
  input         daccess_wresp
);

  wire        _ifu_io_out_ready_T_3;
  wire [31:0] _csr_io_readval;
  wire [31:0] _gpr_io_rs1data;
  wire [31:0] _gpr_io_rs2data;
  wire [31:0] _wbu_io_writeback_data;
  wire        _lsu_io_cacheReq;
  wire        _lsu_io_cacheWrite;
  wire [3:0]  _lsu_io_cacheWStrb;
  wire [31:0] _lsu_io_loadData;
  wire        _lsu_io_busy;
  wire        _lsu_io_loadDone;
  wire        _mulDiv_io_busy;
  wire        _mulDiv_io_done;
  wire [31:0] _mulDiv_io_result;
  wire [31:0] _exu_io_result;
  wire        _idu_io_jalr;
  wire        _idu_io_ecall;
  wire        _idu_io_mret;
  wire        _idu_io_dobranch;
  wire        _idu_io_I;
  wire        _idu_io_S;
  wire        _idu_io_U;
  wire        _idu_io_J;
  wire        _idu_io_R;
  wire [4:0]  _idu_io_rs1addr;
  wire [4:0]  _idu_io_rs2addr;
  wire [4:0]  _idu_io_rdaddr;
  wire        _idu_io_alu_add;
  wire        _idu_io_alu_lh20;
  wire        _idu_io_alu_sub;
  wire        _idu_io_alu_slt;
  wire        _idu_io_alu_sltu;
  wire        _idu_io_alu_xor;
  wire        _idu_io_alu_or;
  wire        _idu_io_alu_and;
  wire        _idu_io_alu_sll;
  wire        _idu_io_alu_srl;
  wire        _idu_io_alu_sra;
  wire        _idu_io_muldiv;
  wire [2:0]  _idu_io_muldiv_funct3;
  wire [31:0] _idu_io_alu_a;
  wire [31:0] _idu_io_alu_b;
  wire        _idu_io_mem_load;
  wire        _idu_io_csr;
  wire        _idu_io_csr_write;
  wire        _idu_io_csr_set;
  wire        _idu_io_csr_clear;
  wire [11:0] _idu_io_csraddr;
  wire        _ifu_io_out_valid;
  wire [31:0] _ifu_io_out_bits_inst;
  wire [31:0] _ifu_io_out_bits_pc;
  wire        ifuFire = _ifu_io_out_valid & _ifu_io_out_ready_T_3;
  wire        memOperation = _idu_io_mem_load | _idu_io_S;
  wire        issueMemory = ifuFire & memOperation;
  wire [31:0] aluResult = _idu_io_muldiv ? _mulDiv_io_result : _exu_io_result;
  reg  [4:0]  memRd;
  wire        mulDivActive = _ifu_io_out_valid & _idu_io_muldiv;
  assign _ifu_io_out_ready_T_3 = ~_lsu_io_busy & (~mulDivActive | _mulDiv_io_done);
  wire        _csr_io_we_T = _idu_io_csr_write & ifuFire;
  always @(posedge cpu_clk) begin
    if (cpu_rst)
      memRd <= 5'h0;
    else if (issueMemory)
      memRd <= _idu_io_rdaddr;
  end // always @(posedge)
  IFU ifu (
    .clock             (cpu_clk),
    .reset             (cpu_rst),
    .io_out_ready      (_ifu_io_out_ready_T_3),
    .io_out_valid      (_ifu_io_out_valid),
    .io_out_bits_inst  (_ifu_io_out_bits_inst),
    .io_out_bits_pc    (_ifu_io_out_bits_pc),
    .io_cacheReq       (ifetch_req),
    .io_cacheAddr      (ifetch_addr),
    .io_cacheRespValid (ifetch_valid),
    .io_cacheRespInst  (ifetch_inst),
    .io_jump
      (ifuFire
       & (_idu_io_dobranch | _idu_io_J | _idu_io_jalr | _idu_io_ecall | _idu_io_mret)),
    .io_jumptarget     (_idu_io_mret ? _csr_io_readval : aluResult),
    .io_stall          (_lsu_io_busy | mulDivActive & ~_mulDiv_io_done)
  );
  IDU idu (
    .io_inst          (_ifu_io_out_bits_inst),
    .io_pc            (_ifu_io_out_bits_pc),
    .io_rs1data       (_gpr_io_rs1data),
    .io_rs2data       (_gpr_io_rs2data),
    .io_jalr          (_idu_io_jalr),
    .io_ecall         (_idu_io_ecall),
    .io_mret          (_idu_io_mret),
    .io_dobranch      (_idu_io_dobranch),
    .io_I             (_idu_io_I),
    .io_S             (_idu_io_S),
    .io_U             (_idu_io_U),
    .io_J             (_idu_io_J),
    .io_R             (_idu_io_R),
    .io_rs1addr       (_idu_io_rs1addr),
    .io_rs2addr       (_idu_io_rs2addr),
    .io_rdaddr        (_idu_io_rdaddr),
    .io_alu_add       (_idu_io_alu_add),
    .io_alu_lh20      (_idu_io_alu_lh20),
    .io_alu_sub       (_idu_io_alu_sub),
    .io_alu_slt       (_idu_io_alu_slt),
    .io_alu_sltu      (_idu_io_alu_sltu),
    .io_alu_xor       (_idu_io_alu_xor),
    .io_alu_or        (_idu_io_alu_or),
    .io_alu_and       (_idu_io_alu_and),
    .io_alu_sll       (_idu_io_alu_sll),
    .io_alu_srl       (_idu_io_alu_srl),
    .io_alu_sra       (_idu_io_alu_sra),
    .io_muldiv        (_idu_io_muldiv),
    .io_muldiv_funct3 (_idu_io_muldiv_funct3),
    .io_alu_a         (_idu_io_alu_a),
    .io_alu_b         (_idu_io_alu_b),
    .io_mem_load      (_idu_io_mem_load),
    .io_csr           (_idu_io_csr),
    .io_csr_write     (_idu_io_csr_write),
    .io_csr_set       (_idu_io_csr_set),
    .io_csr_clear     (_idu_io_csr_clear),
    .io_csraddr       (_idu_io_csraddr)
  );
  EXU exu (
    .io_a      (_idu_io_alu_a),
    .io_b      (_idu_io_alu_b),
    .io_add    (_idu_io_alu_add),
    .io_lh20   (_idu_io_alu_lh20),
    .io_sub    (_idu_io_alu_sub),
    .io_slt    (_idu_io_alu_slt),
    .io_sltu   (_idu_io_alu_sltu),
    .io_xor    (_idu_io_alu_xor),
    .io_or     (_idu_io_alu_or),
    .io_and    (_idu_io_alu_and),
    .io_sll    (_idu_io_alu_sll),
    .io_srl    (_idu_io_alu_srl),
    .io_sra    (_idu_io_alu_sra),
    .io_result (_exu_io_result)
  );
  MulDiv mulDiv (
    .clock     (cpu_clk),
    .reset     (cpu_rst),
    .io_start  (mulDivActive & ~_mulDiv_io_busy & ~_mulDiv_io_done),
    .io_funct3 (_idu_io_muldiv_funct3),
    .io_a      (_idu_io_alu_a),
    .io_b      (_idu_io_alu_b),
    .io_busy   (_mulDiv_io_busy),
    .io_done   (_mulDiv_io_done),
    .io_result (_mulDiv_io_result)
  );
  LSU lsu (
    .clock             (cpu_clk),
    .reset             (cpu_rst),
    .io_exuResult      (aluResult),
    .io_funct3         (_ifu_io_out_bits_inst[14:12]),
    .io_gprRs2Data     (_gpr_io_rs2data),
    .io_load           (issueMemory & _idu_io_mem_load),
    .io_store          (issueMemory & _idu_io_S),
    .io_cacheReq       (_lsu_io_cacheReq),
    .io_cacheWrite     (_lsu_io_cacheWrite),
    .io_cacheAddr      (daccess_addr),
    .io_cacheWData     (daccess_wdata),
    .io_cacheWStrb     (_lsu_io_cacheWStrb),
    .io_cacheRespValid (daccess_rvalid | daccess_wresp),
    .io_cacheRespData  (daccess_rdata),
    .io_loadData       (_lsu_io_loadData),
    .io_busy           (_lsu_io_busy),
    .io_loadDone       (_lsu_io_loadDone)
  );
  WBU wbu (
    .io_exuresult      (aluResult),
    .io_mem_rdata      (_lsu_io_loadData),
    .io_pc             (_ifu_io_out_bits_pc),
    .io_mem_load       (_idu_io_mem_load),
    .io_J              (_idu_io_J),
    .io_jalr           (_idu_io_jalr),
    .io_csr            (_idu_io_csr),
    .io_csrval         (_csr_io_readval),
    .io_writeback_data (_wbu_io_writeback_data)
  );
  GPR gpr (
    .clock      (cpu_clk),
    .reset      (cpu_rst),
    .io_rs1addr (_idu_io_rs1addr),
    .io_rs2addr (_idu_io_rs2addr),
    .io_rdaddr  (_lsu_io_loadDone ? memRd : _idu_io_rdaddr),
    .io_rs1data (_gpr_io_rs1data),
    .io_rs2data (_gpr_io_rs2data),
    .io_rddata  (_lsu_io_loadDone ? _lsu_io_loadData : _wbu_io_writeback_data),
    .io_we
      (ifuFire & ~memOperation & ~_idu_io_S
       & (_idu_io_R | _idu_io_I | _idu_io_U | _idu_io_J | _idu_io_mem_load | _idu_io_csr)
       | _lsu_io_loadDone)
  );
  CSR csr (
    .clock      (cpu_clk),
    .reset      (cpu_rst),
    .io_addr    (_idu_io_csraddr),
    .io_op_val  (_gpr_io_rs1data),
    .io_write   (_csr_io_we_T & ~memOperation),
    .io_set     (_idu_io_csr_set),
    .io_ecall   (_idu_io_ecall & ifuFire & ~memOperation),
    .io_mret    (_idu_io_mret & ifuFire & ~memOperation),
    .io_clear   (_idu_io_csr_clear),
    .io_pc      (_ifu_io_out_bits_pc),
    .io_we      (_csr_io_we_T & ~memOperation),
    .io_readval (_csr_io_readval)
  );
  assign daccess_ren = {4{_lsu_io_cacheReq & ~_lsu_io_cacheWrite}};
  assign daccess_wen = _lsu_io_cacheReq & _lsu_io_cacheWrite ? _lsu_io_cacheWStrb : 4'h0;

`ifdef RUN_TRACE
  wire [31:0] debug_wb_pc    /* verilator public */ ;
  wire        debug_wb_rf_we /* verilator public */ ;
  wire [4:0]  debug_wb_rf_wR /* verilator public */ ;
  wire [31:0] debug_wb_rf_wD /* verilator public */ ;
  wire [31:0] debug_mem_pc    /* verilator public */ ;
  wire [3:0]  debug_mem_we    /* verilator public */ ;
  wire [31:0] debug_mem_waddr /* verilator public */ ;
  wire [31:0] debug_mem_wdata /* verilator public */ ;

  assign debug_wb_pc = _ifu_io_out_bits_pc;
  assign debug_wb_rf_we =
    ifuFire & ~memOperation & ~_idu_io_S
    & (_idu_io_R | _idu_io_I | _idu_io_U | _idu_io_J | _idu_io_mem_load | _idu_io_csr)
    | _lsu_io_loadDone;
  assign debug_wb_rf_wR = _lsu_io_loadDone ? memRd : _idu_io_rdaddr;
  assign debug_wb_rf_wD = _lsu_io_loadDone ? _lsu_io_loadData : _wbu_io_writeback_data;
  assign debug_mem_pc = _ifu_io_out_bits_pc;
  assign debug_mem_we = daccess_wen;
  assign debug_mem_waddr = daccess_addr;
  assign debug_mem_wdata = daccess_wdata;
`endif

endmodule

