`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module cpu_top(
  input         io_cpu_clk,
                io_cpu_rst,
  output [3:0]  io_pmem_axi_ar_arid,
  output [31:0] io_pmem_axi_ar_araddr,
  output [7:0]  io_pmem_axi_ar_arlen,
  output [2:0]  io_pmem_axi_ar_arsize,
  output [1:0]  io_pmem_axi_ar_arburst,
  output        io_pmem_axi_ar_arlock,
  output [3:0]  io_pmem_axi_ar_arcache,
  output [2:0]  io_pmem_axi_ar_arprot,
  output [3:0]  io_pmem_axi_ar_arqos,
                io_pmem_axi_ar_arregion,
  output        io_pmem_axi_ar_arvalid,
  input         io_pmem_axi_ar_arready,
  input  [3:0]  io_pmem_axi_r_rid,
  input  [31:0] io_pmem_axi_r_rdata,
  input  [1:0]  io_pmem_axi_r_rresp,
  input         io_pmem_axi_r_rlast,
                io_pmem_axi_r_rvalid,
  output        io_pmem_axi_r_rready,
  output [3:0]  io_pmem_axi_aw_awid,
  output [31:0] io_pmem_axi_aw_awaddr,
  output [7:0]  io_pmem_axi_aw_awlen,
  output [2:0]  io_pmem_axi_aw_awsize,
  output [1:0]  io_pmem_axi_aw_awburst,
  output        io_pmem_axi_aw_awlock,
  output [3:0]  io_pmem_axi_aw_awcache,
  output [2:0]  io_pmem_axi_aw_awprot,
  output [3:0]  io_pmem_axi_aw_awqos,
                io_pmem_axi_aw_awregion,
  output        io_pmem_axi_aw_awvalid,
  input         io_pmem_axi_aw_awready,
  output [31:0] io_pmem_axi_w_wdata,
  output [3:0]  io_pmem_axi_w_wstrb,
  output        io_pmem_axi_w_wlast,
                io_pmem_axi_w_wvalid,
  input         io_pmem_axi_w_wready,
  input  [3:0]  io_pmem_axi_b_bid,
  input  [1:0]  io_pmem_axi_b_bresp,
  input         io_pmem_axi_b_bvalid,
  output        io_pmem_axi_b_bready,
  output [31:0] io_inst,
                io_pc
);

  wire        _axiMaster_io_icache_axi_ar_arready;
  wire [31:0] _axiMaster_io_icache_axi_r_rdata;
  wire        _axiMaster_io_icache_axi_r_rlast;
  wire        _axiMaster_io_icache_axi_r_rvalid;
  wire        _axiMaster_io_lsu_axi_ar_arready;
  wire [31:0] _axiMaster_io_lsu_axi_r_rdata;
  wire        _axiMaster_io_lsu_axi_r_rlast;
  wire        _axiMaster_io_lsu_axi_r_rvalid;
  wire        _axiMaster_io_lsu_axi_aw_awready;
  wire        _axiMaster_io_lsu_axi_w_wready;
  wire        _axiMaster_io_lsu_axi_b_bvalid;
  wire        _dcache_io_cpuRespValid;
  wire [31:0] _dcache_io_cpuRespData;
  wire [31:0] _dcache_io_axi_ar_araddr;
  wire [7:0]  _dcache_io_axi_ar_arlen;
  wire        _dcache_io_axi_ar_arvalid;
  wire        _dcache_io_axi_r_rready;
  wire [31:0] _dcache_io_axi_aw_awaddr;
  wire        _dcache_io_axi_aw_awvalid;
  wire [31:0] _dcache_io_axi_w_wdata;
  wire [3:0]  _dcache_io_axi_w_wstrb;
  wire        _dcache_io_axi_w_wvalid;
  wire        _dcache_io_axi_b_bready;
  wire        _icache_io_cpuRespValid;
  wire [31:0] _icache_io_cpuRespInst;
  wire [31:0] _icache_io_axi_ar_araddr;
  wire        _icache_io_axi_ar_arvalid;
  wire        _icache_io_axi_r_rready;
  wire        _U_core_ifetch_req;
  wire [31:0] _U_core_ifetch_addr;
  wire [3:0]  _U_core_daccess_ren;
  wire [31:0] _U_core_daccess_addr;
  wire [3:0]  _U_core_daccess_wen;
  wire [31:0] _U_core_daccess_wdata;
  cpu_core U_core (
    .cpu_rst        (io_cpu_rst),
    .cpu_clk        (io_cpu_clk),
    .ifetch_req     (_U_core_ifetch_req),
    .ifetch_addr    (_U_core_ifetch_addr),
    .ifetch_valid   (_icache_io_cpuRespValid),
    .ifetch_inst    (_icache_io_cpuRespInst),
    .daccess_ren    (_U_core_daccess_ren),
    .daccess_addr   (_U_core_daccess_addr),
    .daccess_rvalid (_dcache_io_cpuRespValid),
    .daccess_rdata  (_dcache_io_cpuRespData),
    .daccess_wen    (_U_core_daccess_wen),
    .daccess_wdata  (_U_core_daccess_wdata),
    .daccess_wresp  (_dcache_io_cpuRespValid)
  );
  ICache icache (
    .clock             (io_cpu_clk),
    .reset             (io_cpu_rst),
    .io_cpuReq         (_U_core_ifetch_req),
    .io_cpuAddr        (_U_core_ifetch_addr),
    .io_cpuRespValid   (_icache_io_cpuRespValid),
    .io_cpuRespInst    (_icache_io_cpuRespInst),
    .io_axi_ar_araddr  (_icache_io_axi_ar_araddr),
    .io_axi_ar_arvalid (_icache_io_axi_ar_arvalid),
    .io_axi_ar_arready (_axiMaster_io_icache_axi_ar_arready),
    .io_axi_r_rdata    (_axiMaster_io_icache_axi_r_rdata),
    .io_axi_r_rlast    (_axiMaster_io_icache_axi_r_rlast),
    .io_axi_r_rvalid   (_axiMaster_io_icache_axi_r_rvalid),
    .io_axi_r_rready   (_icache_io_axi_r_rready)
  );
  DCache dcache (
    .clock             (io_cpu_clk),
    .reset             (io_cpu_rst),
    .io_cpuReq         ((|_U_core_daccess_ren) | (|_U_core_daccess_wen)),
    .io_cpuWrite       (|_U_core_daccess_wen),
    .io_cpuAddr        (_U_core_daccess_addr),
    .io_cpuWData       (_U_core_daccess_wdata),
    .io_cpuWStrb       (_U_core_daccess_wen),
    .io_cpuRespValid   (_dcache_io_cpuRespValid),
    .io_cpuRespData    (_dcache_io_cpuRespData),
    .io_axi_ar_araddr  (_dcache_io_axi_ar_araddr),
    .io_axi_ar_arlen   (_dcache_io_axi_ar_arlen),
    .io_axi_ar_arvalid (_dcache_io_axi_ar_arvalid),
    .io_axi_ar_arready (_axiMaster_io_lsu_axi_ar_arready),
    .io_axi_r_rdata    (_axiMaster_io_lsu_axi_r_rdata),
    .io_axi_r_rlast    (_axiMaster_io_lsu_axi_r_rlast),
    .io_axi_r_rvalid   (_axiMaster_io_lsu_axi_r_rvalid),
    .io_axi_r_rready   (_dcache_io_axi_r_rready),
    .io_axi_aw_awaddr  (_dcache_io_axi_aw_awaddr),
    .io_axi_aw_awvalid (_dcache_io_axi_aw_awvalid),
    .io_axi_aw_awready (_axiMaster_io_lsu_axi_aw_awready),
    .io_axi_w_wdata    (_dcache_io_axi_w_wdata),
    .io_axi_w_wstrb    (_dcache_io_axi_w_wstrb),
    .io_axi_w_wvalid   (_dcache_io_axi_w_wvalid),
    .io_axi_w_wready   (_axiMaster_io_lsu_axi_w_wready),
    .io_axi_b_bvalid   (_axiMaster_io_lsu_axi_b_bvalid),
    .io_axi_b_bready   (_dcache_io_axi_b_bready)
  );
  AXI_Master axiMaster (
    .clock                    (io_cpu_clk),
    .reset                    (io_cpu_rst),
    .io_icache_axi_ar_araddr  (_icache_io_axi_ar_araddr),
    .io_icache_axi_ar_arvalid (_icache_io_axi_ar_arvalid),
    .io_icache_axi_ar_arready (_axiMaster_io_icache_axi_ar_arready),
    .io_icache_axi_r_rdata    (_axiMaster_io_icache_axi_r_rdata),
    .io_icache_axi_r_rlast    (_axiMaster_io_icache_axi_r_rlast),
    .io_icache_axi_r_rvalid   (_axiMaster_io_icache_axi_r_rvalid),
    .io_icache_axi_r_rready   (_icache_io_axi_r_rready),
    .io_lsu_axi_ar_araddr     (_dcache_io_axi_ar_araddr),
    .io_lsu_axi_ar_arlen      (_dcache_io_axi_ar_arlen),
    .io_lsu_axi_ar_arvalid    (_dcache_io_axi_ar_arvalid),
    .io_lsu_axi_ar_arready    (_axiMaster_io_lsu_axi_ar_arready),
    .io_lsu_axi_r_rdata       (_axiMaster_io_lsu_axi_r_rdata),
    .io_lsu_axi_r_rlast       (_axiMaster_io_lsu_axi_r_rlast),
    .io_lsu_axi_r_rvalid      (_axiMaster_io_lsu_axi_r_rvalid),
    .io_lsu_axi_r_rready      (_dcache_io_axi_r_rready),
    .io_lsu_axi_aw_awaddr     (_dcache_io_axi_aw_awaddr),
    .io_lsu_axi_aw_awvalid    (_dcache_io_axi_aw_awvalid),
    .io_lsu_axi_aw_awready    (_axiMaster_io_lsu_axi_aw_awready),
    .io_lsu_axi_w_wdata       (_dcache_io_axi_w_wdata),
    .io_lsu_axi_w_wstrb       (_dcache_io_axi_w_wstrb),
    .io_lsu_axi_w_wvalid      (_dcache_io_axi_w_wvalid),
    .io_lsu_axi_w_wready      (_axiMaster_io_lsu_axi_w_wready),
    .io_lsu_axi_b_bvalid      (_axiMaster_io_lsu_axi_b_bvalid),
    .io_lsu_axi_b_bready      (_dcache_io_axi_b_bready),
    .io_pmem_axi_ar_arid      (io_pmem_axi_ar_arid),
    .io_pmem_axi_ar_araddr    (io_pmem_axi_ar_araddr),
    .io_pmem_axi_ar_arlen     (io_pmem_axi_ar_arlen),
    .io_pmem_axi_ar_arprot    (io_pmem_axi_ar_arprot),
    .io_pmem_axi_ar_arvalid   (io_pmem_axi_ar_arvalid),
    .io_pmem_axi_ar_arready   (io_pmem_axi_ar_arready),
    .io_pmem_axi_r_rdata      (io_pmem_axi_r_rdata),
    .io_pmem_axi_r_rlast      (io_pmem_axi_r_rlast),
    .io_pmem_axi_r_rvalid     (io_pmem_axi_r_rvalid),
    .io_pmem_axi_r_rready     (io_pmem_axi_r_rready),
    .io_pmem_axi_aw_awaddr    (io_pmem_axi_aw_awaddr),
    .io_pmem_axi_aw_awvalid   (io_pmem_axi_aw_awvalid),
    .io_pmem_axi_aw_awready   (io_pmem_axi_aw_awready),
    .io_pmem_axi_w_wdata      (io_pmem_axi_w_wdata),
    .io_pmem_axi_w_wstrb      (io_pmem_axi_w_wstrb),
    .io_pmem_axi_w_wvalid     (io_pmem_axi_w_wvalid),
    .io_pmem_axi_w_wready     (io_pmem_axi_w_wready),
    .io_pmem_axi_b_bvalid     (io_pmem_axi_b_bvalid),
    .io_pmem_axi_b_bready     (io_pmem_axi_b_bready)
  );
  assign io_pmem_axi_ar_arsize = 3'h2;
  assign io_pmem_axi_ar_arburst = 2'h1;
  assign io_pmem_axi_ar_arlock = 1'h0;
  assign io_pmem_axi_ar_arcache = 4'h0;
  assign io_pmem_axi_ar_arqos = 4'h0;
  assign io_pmem_axi_ar_arregion = 4'h0;
  assign io_pmem_axi_aw_awid = 4'h1;
  assign io_pmem_axi_aw_awlen = 8'h0;
  assign io_pmem_axi_aw_awsize = 3'h2;
  assign io_pmem_axi_aw_awburst = 2'h1;
  assign io_pmem_axi_aw_awlock = 1'h0;
  assign io_pmem_axi_aw_awcache = 4'h0;
  assign io_pmem_axi_aw_awprot = 3'h0;
  assign io_pmem_axi_aw_awqos = 4'h0;
  assign io_pmem_axi_aw_awregion = 4'h0;
  assign io_pmem_axi_w_wlast = 1'h1;
  assign io_inst = 32'h0;
  assign io_pc = 32'h0;
endmodule

