`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module EXU(
  input  [31:0] io_a,
                io_b,
  input         io_add,
                io_lh20,
                io_sub,
                io_slt,
                io_sltu,
                io_xor,
                io_or,
                io_and,
                io_sll,
                io_srl,
                io_sra,
                io_mul,
                io_mulh,
                io_mulsu,
                io_mulu,
                io_div,
                io_divu,
                io_rem,
                io_remu,
  output [31:0] io_result
);

  wire [31:0] _io_result_T_3 = io_a + io_b;
  wire [62:0] _io_result_T_27 = {31'h0, io_a} << io_b[4:0];
  wire [31:0] _GEN = {27'h0, io_b[4:0]};
  wire [63:0] _GEN_0 = {{32{io_a[31]}}, io_a};
  wire [63:0] _io_result_T_36 = _GEN_0 * {{32{io_b[31]}}, io_b};
  wire [63:0] _GEN_1 = {32'h0, io_b};
  wire [63:0] _io_result_T_41 = _GEN_0 * _GEN_1;
  wire [63:0] _io_result_T_48 = {32'h0, io_a} * _GEN_1;
  wire [32:0] _io_result_T_51 = $signed({io_a[31], io_a}) / $signed({io_b[31], io_b});
  wire        _io_result_signedMagnitude_T = $signed(io_a) < 32'sh0;
  wire [31:0] io_result_dividendAbs = _io_result_signedMagnitude_T ? ~io_a + 32'h1 : io_a;
  wire [31:0] io_result_divisorAbs = $signed(io_b) < 32'sh0 ? ~io_b + 32'h1 : io_b;
  wire [32:0] io_result_magnitude_extendedDivisor = {1'h0, io_result_divisorAbs};
  wire [31:0] _GEN_2 = {31'h0, io_result_dividendAbs[31]};
  wire [31:0] _io_result_magnitude_T_3 =
    {32'h0, io_result_dividendAbs[31]} >= io_result_magnitude_extendedDivisor
      ? _GEN_2 - io_result_divisorAbs
      : _GEN_2;
  wire [31:0] _GEN_3 = {_io_result_magnitude_T_3[30:0], io_result_dividendAbs[30]};
  wire [31:0] _io_result_magnitude_T_7 =
    {_io_result_magnitude_T_3,
     io_result_dividendAbs[30]} >= io_result_magnitude_extendedDivisor
      ? _GEN_3 - io_result_divisorAbs
      : _GEN_3;
  wire [31:0] _GEN_4 = {_io_result_magnitude_T_7[30:0], io_result_dividendAbs[29]};
  wire [31:0] _io_result_magnitude_T_11 =
    {_io_result_magnitude_T_7,
     io_result_dividendAbs[29]} >= io_result_magnitude_extendedDivisor
      ? _GEN_4 - io_result_divisorAbs
      : _GEN_4;
  wire [31:0] _GEN_5 = {_io_result_magnitude_T_11[30:0], io_result_dividendAbs[28]};
  wire [31:0] _io_result_magnitude_T_15 =
    {_io_result_magnitude_T_11,
     io_result_dividendAbs[28]} >= io_result_magnitude_extendedDivisor
      ? _GEN_5 - io_result_divisorAbs
      : _GEN_5;
  wire [31:0] _GEN_6 = {_io_result_magnitude_T_15[30:0], io_result_dividendAbs[27]};
  wire [31:0] _io_result_magnitude_T_19 =
    {_io_result_magnitude_T_15,
     io_result_dividendAbs[27]} >= io_result_magnitude_extendedDivisor
      ? _GEN_6 - io_result_divisorAbs
      : _GEN_6;
  wire [31:0] _GEN_7 = {_io_result_magnitude_T_19[30:0], io_result_dividendAbs[26]};
  wire [31:0] _io_result_magnitude_T_23 =
    {_io_result_magnitude_T_19,
     io_result_dividendAbs[26]} >= io_result_magnitude_extendedDivisor
      ? _GEN_7 - io_result_divisorAbs
      : _GEN_7;
  wire [31:0] _GEN_8 = {_io_result_magnitude_T_23[30:0], io_result_dividendAbs[25]};
  wire [31:0] _io_result_magnitude_T_27 =
    {_io_result_magnitude_T_23,
     io_result_dividendAbs[25]} >= io_result_magnitude_extendedDivisor
      ? _GEN_8 - io_result_divisorAbs
      : _GEN_8;
  wire [31:0] _GEN_9 = {_io_result_magnitude_T_27[30:0], io_result_dividendAbs[24]};
  wire [31:0] _io_result_magnitude_T_31 =
    {_io_result_magnitude_T_27,
     io_result_dividendAbs[24]} >= io_result_magnitude_extendedDivisor
      ? _GEN_9 - io_result_divisorAbs
      : _GEN_9;
  wire [31:0] _GEN_10 = {_io_result_magnitude_T_31[30:0], io_result_dividendAbs[23]};
  wire [31:0] _io_result_magnitude_T_35 =
    {_io_result_magnitude_T_31,
     io_result_dividendAbs[23]} >= io_result_magnitude_extendedDivisor
      ? _GEN_10 - io_result_divisorAbs
      : _GEN_10;
  wire [31:0] _GEN_11 = {_io_result_magnitude_T_35[30:0], io_result_dividendAbs[22]};
  wire [31:0] _io_result_magnitude_T_39 =
    {_io_result_magnitude_T_35,
     io_result_dividendAbs[22]} >= io_result_magnitude_extendedDivisor
      ? _GEN_11 - io_result_divisorAbs
      : _GEN_11;
  wire [31:0] _GEN_12 = {_io_result_magnitude_T_39[30:0], io_result_dividendAbs[21]};
  wire [31:0] _io_result_magnitude_T_43 =
    {_io_result_magnitude_T_39,
     io_result_dividendAbs[21]} >= io_result_magnitude_extendedDivisor
      ? _GEN_12 - io_result_divisorAbs
      : _GEN_12;
  wire [31:0] _GEN_13 = {_io_result_magnitude_T_43[30:0], io_result_dividendAbs[20]};
  wire [31:0] _io_result_magnitude_T_47 =
    {_io_result_magnitude_T_43,
     io_result_dividendAbs[20]} >= io_result_magnitude_extendedDivisor
      ? _GEN_13 - io_result_divisorAbs
      : _GEN_13;
  wire [31:0] _GEN_14 = {_io_result_magnitude_T_47[30:0], io_result_dividendAbs[19]};
  wire [31:0] _io_result_magnitude_T_51 =
    {_io_result_magnitude_T_47,
     io_result_dividendAbs[19]} >= io_result_magnitude_extendedDivisor
      ? _GEN_14 - io_result_divisorAbs
      : _GEN_14;
  wire [31:0] _GEN_15 = {_io_result_magnitude_T_51[30:0], io_result_dividendAbs[18]};
  wire [31:0] _io_result_magnitude_T_55 =
    {_io_result_magnitude_T_51,
     io_result_dividendAbs[18]} >= io_result_magnitude_extendedDivisor
      ? _GEN_15 - io_result_divisorAbs
      : _GEN_15;
  wire [31:0] _GEN_16 = {_io_result_magnitude_T_55[30:0], io_result_dividendAbs[17]};
  wire [31:0] _io_result_magnitude_T_59 =
    {_io_result_magnitude_T_55,
     io_result_dividendAbs[17]} >= io_result_magnitude_extendedDivisor
      ? _GEN_16 - io_result_divisorAbs
      : _GEN_16;
  wire [31:0] _GEN_17 = {_io_result_magnitude_T_59[30:0], io_result_dividendAbs[16]};
  wire [31:0] _io_result_magnitude_T_63 =
    {_io_result_magnitude_T_59,
     io_result_dividendAbs[16]} >= io_result_magnitude_extendedDivisor
      ? _GEN_17 - io_result_divisorAbs
      : _GEN_17;
  wire [31:0] _GEN_18 = {_io_result_magnitude_T_63[30:0], io_result_dividendAbs[15]};
  wire [31:0] _io_result_magnitude_T_67 =
    {_io_result_magnitude_T_63,
     io_result_dividendAbs[15]} >= io_result_magnitude_extendedDivisor
      ? _GEN_18 - io_result_divisorAbs
      : _GEN_18;
  wire [31:0] _GEN_19 = {_io_result_magnitude_T_67[30:0], io_result_dividendAbs[14]};
  wire [31:0] _io_result_magnitude_T_71 =
    {_io_result_magnitude_T_67,
     io_result_dividendAbs[14]} >= io_result_magnitude_extendedDivisor
      ? _GEN_19 - io_result_divisorAbs
      : _GEN_19;
  wire [31:0] _GEN_20 = {_io_result_magnitude_T_71[30:0], io_result_dividendAbs[13]};
  wire [31:0] _io_result_magnitude_T_75 =
    {_io_result_magnitude_T_71,
     io_result_dividendAbs[13]} >= io_result_magnitude_extendedDivisor
      ? _GEN_20 - io_result_divisorAbs
      : _GEN_20;
  wire [31:0] _GEN_21 = {_io_result_magnitude_T_75[30:0], io_result_dividendAbs[12]};
  wire [31:0] _io_result_magnitude_T_79 =
    {_io_result_magnitude_T_75,
     io_result_dividendAbs[12]} >= io_result_magnitude_extendedDivisor
      ? _GEN_21 - io_result_divisorAbs
      : _GEN_21;
  wire [31:0] _GEN_22 = {_io_result_magnitude_T_79[30:0], io_result_dividendAbs[11]};
  wire [31:0] _io_result_magnitude_T_83 =
    {_io_result_magnitude_T_79,
     io_result_dividendAbs[11]} >= io_result_magnitude_extendedDivisor
      ? _GEN_22 - io_result_divisorAbs
      : _GEN_22;
  wire [31:0] _GEN_23 = {_io_result_magnitude_T_83[30:0], io_result_dividendAbs[10]};
  wire [31:0] _io_result_magnitude_T_87 =
    {_io_result_magnitude_T_83,
     io_result_dividendAbs[10]} >= io_result_magnitude_extendedDivisor
      ? _GEN_23 - io_result_divisorAbs
      : _GEN_23;
  wire [31:0] _GEN_24 = {_io_result_magnitude_T_87[30:0], io_result_dividendAbs[9]};
  wire [31:0] _io_result_magnitude_T_91 =
    {_io_result_magnitude_T_87,
     io_result_dividendAbs[9]} >= io_result_magnitude_extendedDivisor
      ? _GEN_24 - io_result_divisorAbs
      : _GEN_24;
  wire [31:0] _GEN_25 = {_io_result_magnitude_T_91[30:0], io_result_dividendAbs[8]};
  wire [31:0] _io_result_magnitude_T_95 =
    {_io_result_magnitude_T_91,
     io_result_dividendAbs[8]} >= io_result_magnitude_extendedDivisor
      ? _GEN_25 - io_result_divisorAbs
      : _GEN_25;
  wire [31:0] _GEN_26 = {_io_result_magnitude_T_95[30:0], io_result_dividendAbs[7]};
  wire [31:0] _io_result_magnitude_T_99 =
    {_io_result_magnitude_T_95,
     io_result_dividendAbs[7]} >= io_result_magnitude_extendedDivisor
      ? _GEN_26 - io_result_divisorAbs
      : _GEN_26;
  wire [31:0] _GEN_27 = {_io_result_magnitude_T_99[30:0], io_result_dividendAbs[6]};
  wire [31:0] _io_result_magnitude_T_103 =
    {_io_result_magnitude_T_99,
     io_result_dividendAbs[6]} >= io_result_magnitude_extendedDivisor
      ? _GEN_27 - io_result_divisorAbs
      : _GEN_27;
  wire [31:0] _GEN_28 = {_io_result_magnitude_T_103[30:0], io_result_dividendAbs[5]};
  wire [31:0] _io_result_magnitude_T_107 =
    {_io_result_magnitude_T_103,
     io_result_dividendAbs[5]} >= io_result_magnitude_extendedDivisor
      ? _GEN_28 - io_result_divisorAbs
      : _GEN_28;
  wire [31:0] _GEN_29 = {_io_result_magnitude_T_107[30:0], io_result_dividendAbs[4]};
  wire [31:0] _io_result_magnitude_T_111 =
    {_io_result_magnitude_T_107,
     io_result_dividendAbs[4]} >= io_result_magnitude_extendedDivisor
      ? _GEN_29 - io_result_divisorAbs
      : _GEN_29;
  wire [31:0] _GEN_30 = {_io_result_magnitude_T_111[30:0], io_result_dividendAbs[3]};
  wire [31:0] _io_result_magnitude_T_115 =
    {_io_result_magnitude_T_111,
     io_result_dividendAbs[3]} >= io_result_magnitude_extendedDivisor
      ? _GEN_30 - io_result_divisorAbs
      : _GEN_30;
  wire [31:0] _GEN_31 = {_io_result_magnitude_T_115[30:0], io_result_dividendAbs[2]};
  wire [31:0] _io_result_magnitude_T_119 =
    {_io_result_magnitude_T_115,
     io_result_dividendAbs[2]} >= io_result_magnitude_extendedDivisor
      ? _GEN_31 - io_result_divisorAbs
      : _GEN_31;
  wire [31:0] _GEN_32 = {_io_result_magnitude_T_119[30:0], io_result_dividendAbs[1]};
  wire [31:0] _io_result_magnitude_T_123 =
    {_io_result_magnitude_T_119,
     io_result_dividendAbs[1]} >= io_result_magnitude_extendedDivisor
      ? _GEN_32 - io_result_divisorAbs
      : _GEN_32;
  wire [31:0] _GEN_33 = {_io_result_magnitude_T_123[30:0], io_result_dividendAbs[0]};
  wire [31:0] _io_result_magnitude_T_127 =
    {_io_result_magnitude_T_123,
     io_result_dividendAbs[0]} >= io_result_magnitude_extendedDivisor
      ? _GEN_33 - io_result_divisorAbs
      : _GEN_33;
  wire        _io_result_T_58 = io_b == 32'h0;
  wire [32:0] io_result_extendedDivisor = {1'h0, io_b};
  wire [31:0] _GEN_34 = {31'h0, io_a[31]};
  wire [31:0] _io_result_T_64 =
    {32'h0, io_a[31]} >= io_result_extendedDivisor ? _GEN_34 - io_b : _GEN_34;
  wire [31:0] _GEN_35 = {_io_result_T_64[30:0], io_a[30]};
  wire [31:0] _io_result_T_68 =
    {_io_result_T_64, io_a[30]} >= io_result_extendedDivisor ? _GEN_35 - io_b : _GEN_35;
  wire [31:0] _GEN_36 = {_io_result_T_68[30:0], io_a[29]};
  wire [31:0] _io_result_T_72 =
    {_io_result_T_68, io_a[29]} >= io_result_extendedDivisor ? _GEN_36 - io_b : _GEN_36;
  wire [31:0] _GEN_37 = {_io_result_T_72[30:0], io_a[28]};
  wire [31:0] _io_result_T_76 =
    {_io_result_T_72, io_a[28]} >= io_result_extendedDivisor ? _GEN_37 - io_b : _GEN_37;
  wire [31:0] _GEN_38 = {_io_result_T_76[30:0], io_a[27]};
  wire [31:0] _io_result_T_80 =
    {_io_result_T_76, io_a[27]} >= io_result_extendedDivisor ? _GEN_38 - io_b : _GEN_38;
  wire [31:0] _GEN_39 = {_io_result_T_80[30:0], io_a[26]};
  wire [31:0] _io_result_T_84 =
    {_io_result_T_80, io_a[26]} >= io_result_extendedDivisor ? _GEN_39 - io_b : _GEN_39;
  wire [31:0] _GEN_40 = {_io_result_T_84[30:0], io_a[25]};
  wire [31:0] _io_result_T_88 =
    {_io_result_T_84, io_a[25]} >= io_result_extendedDivisor ? _GEN_40 - io_b : _GEN_40;
  wire [31:0] _GEN_41 = {_io_result_T_88[30:0], io_a[24]};
  wire [31:0] _io_result_T_92 =
    {_io_result_T_88, io_a[24]} >= io_result_extendedDivisor ? _GEN_41 - io_b : _GEN_41;
  wire [31:0] _GEN_42 = {_io_result_T_92[30:0], io_a[23]};
  wire [31:0] _io_result_T_96 =
    {_io_result_T_92, io_a[23]} >= io_result_extendedDivisor ? _GEN_42 - io_b : _GEN_42;
  wire [31:0] _GEN_43 = {_io_result_T_96[30:0], io_a[22]};
  wire [31:0] _io_result_T_100 =
    {_io_result_T_96, io_a[22]} >= io_result_extendedDivisor ? _GEN_43 - io_b : _GEN_43;
  wire [31:0] _GEN_44 = {_io_result_T_100[30:0], io_a[21]};
  wire [31:0] _io_result_T_104 =
    {_io_result_T_100, io_a[21]} >= io_result_extendedDivisor ? _GEN_44 - io_b : _GEN_44;
  wire [31:0] _GEN_45 = {_io_result_T_104[30:0], io_a[20]};
  wire [31:0] _io_result_T_108 =
    {_io_result_T_104, io_a[20]} >= io_result_extendedDivisor ? _GEN_45 - io_b : _GEN_45;
  wire [31:0] _GEN_46 = {_io_result_T_108[30:0], io_a[19]};
  wire [31:0] _io_result_T_112 =
    {_io_result_T_108, io_a[19]} >= io_result_extendedDivisor ? _GEN_46 - io_b : _GEN_46;
  wire [31:0] _GEN_47 = {_io_result_T_112[30:0], io_a[18]};
  wire [31:0] _io_result_T_116 =
    {_io_result_T_112, io_a[18]} >= io_result_extendedDivisor ? _GEN_47 - io_b : _GEN_47;
  wire [31:0] _GEN_48 = {_io_result_T_116[30:0], io_a[17]};
  wire [31:0] _io_result_T_120 =
    {_io_result_T_116, io_a[17]} >= io_result_extendedDivisor ? _GEN_48 - io_b : _GEN_48;
  wire [31:0] _GEN_49 = {_io_result_T_120[30:0], io_a[16]};
  wire [31:0] _io_result_T_124 =
    {_io_result_T_120, io_a[16]} >= io_result_extendedDivisor ? _GEN_49 - io_b : _GEN_49;
  wire [31:0] _GEN_50 = {_io_result_T_124[30:0], io_a[15]};
  wire [31:0] _io_result_T_128 =
    {_io_result_T_124, io_a[15]} >= io_result_extendedDivisor ? _GEN_50 - io_b : _GEN_50;
  wire [31:0] _GEN_51 = {_io_result_T_128[30:0], io_a[14]};
  wire [31:0] _io_result_T_132 =
    {_io_result_T_128, io_a[14]} >= io_result_extendedDivisor ? _GEN_51 - io_b : _GEN_51;
  wire [31:0] _GEN_52 = {_io_result_T_132[30:0], io_a[13]};
  wire [31:0] _io_result_T_136 =
    {_io_result_T_132, io_a[13]} >= io_result_extendedDivisor ? _GEN_52 - io_b : _GEN_52;
  wire [31:0] _GEN_53 = {_io_result_T_136[30:0], io_a[12]};
  wire [31:0] _io_result_T_140 =
    {_io_result_T_136, io_a[12]} >= io_result_extendedDivisor ? _GEN_53 - io_b : _GEN_53;
  wire [31:0] _GEN_54 = {_io_result_T_140[30:0], io_a[11]};
  wire [31:0] _io_result_T_144 =
    {_io_result_T_140, io_a[11]} >= io_result_extendedDivisor ? _GEN_54 - io_b : _GEN_54;
  wire [31:0] _GEN_55 = {_io_result_T_144[30:0], io_a[10]};
  wire [31:0] _io_result_T_148 =
    {_io_result_T_144, io_a[10]} >= io_result_extendedDivisor ? _GEN_55 - io_b : _GEN_55;
  wire [31:0] _GEN_56 = {_io_result_T_148[30:0], io_a[9]};
  wire [31:0] _io_result_T_152 =
    {_io_result_T_148, io_a[9]} >= io_result_extendedDivisor ? _GEN_56 - io_b : _GEN_56;
  wire [31:0] _GEN_57 = {_io_result_T_152[30:0], io_a[8]};
  wire [31:0] _io_result_T_156 =
    {_io_result_T_152, io_a[8]} >= io_result_extendedDivisor ? _GEN_57 - io_b : _GEN_57;
  wire [31:0] _GEN_58 = {_io_result_T_156[30:0], io_a[7]};
  wire [31:0] _io_result_T_160 =
    {_io_result_T_156, io_a[7]} >= io_result_extendedDivisor ? _GEN_58 - io_b : _GEN_58;
  wire [31:0] _GEN_59 = {_io_result_T_160[30:0], io_a[6]};
  wire [31:0] _io_result_T_164 =
    {_io_result_T_160, io_a[6]} >= io_result_extendedDivisor ? _GEN_59 - io_b : _GEN_59;
  wire [31:0] _GEN_60 = {_io_result_T_164[30:0], io_a[5]};
  wire [31:0] _io_result_T_168 =
    {_io_result_T_164, io_a[5]} >= io_result_extendedDivisor ? _GEN_60 - io_b : _GEN_60;
  wire [31:0] _GEN_61 = {_io_result_T_168[30:0], io_a[4]};
  wire [31:0] _io_result_T_172 =
    {_io_result_T_168, io_a[4]} >= io_result_extendedDivisor ? _GEN_61 - io_b : _GEN_61;
  wire [31:0] _GEN_62 = {_io_result_T_172[30:0], io_a[3]};
  wire [31:0] _io_result_T_176 =
    {_io_result_T_172, io_a[3]} >= io_result_extendedDivisor ? _GEN_62 - io_b : _GEN_62;
  wire [31:0] _GEN_63 = {_io_result_T_176[30:0], io_a[2]};
  wire [31:0] _io_result_T_180 =
    {_io_result_T_176, io_a[2]} >= io_result_extendedDivisor ? _GEN_63 - io_b : _GEN_63;
  wire [31:0] _GEN_64 = {_io_result_T_180[30:0], io_a[1]};
  wire [31:0] _io_result_T_184 =
    {_io_result_T_180, io_a[1]} >= io_result_extendedDivisor ? _GEN_64 - io_b : _GEN_64;
  wire [31:0] _GEN_65 = {_io_result_T_184[30:0], io_a[0]};
  assign io_result =
    io_add
      ? _io_result_T_3
      : io_lh20
          ? io_b
          : io_sub
              ? io_a - io_b
              : io_slt
                  ? {31'h0, $signed(io_a) < $signed(io_b)}
                  : io_sltu
                      ? {31'h0, io_a < io_b}
                      : io_xor
                          ? io_a ^ io_b
                          : io_or
                              ? io_a | io_b
                              : io_and
                                  ? io_a & io_b
                                  : io_sll
                                      ? _io_result_T_27[31:0]
                                      : io_srl
                                          ? io_a >> _GEN
                                          : io_sra
                                              ? $signed($signed(io_a) >>> _GEN)
                                              : io_mul
                                                  ? _io_result_T_36[31:0]
                                                  : io_mulh
                                                      ? _io_result_T_36[63:32]
                                                      : io_mulsu
                                                          ? _io_result_T_41[63:32]
                                                          : io_mulu
                                                              ? _io_result_T_48[63:32]
                                                              : io_div
                                                                  ? _io_result_T_51[31:0]
                                                                  : io_divu
                                                                      ? io_a / io_b
                                                                      : io_rem
                                                                          ? (_io_result_T_58
                                                                               ? io_a
                                                                               : _io_result_signedMagnitude_T
                                                                                   ? ~_io_result_magnitude_T_127
                                                                                     + 32'h1
                                                                                   : _io_result_magnitude_T_127)
                                                                          : io_remu
                                                                              ? (_io_result_T_58
                                                                                   ? io_a
                                                                                   : {_io_result_T_184,
                                                                                      io_a[0]} >= io_result_extendedDivisor
                                                                                       ? _GEN_65
                                                                                         - io_b
                                                                                       : _GEN_65)
                                                                              : _io_result_T_3;
endmodule

