`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module EXU(
  input  [31:0] io_a,
                io_b,
  input         io_add,
                io_lh20,
                io_sub,
                io_slt,
                io_sltu,
                io_xor,
                io_or,
                io_and,
                io_sll,
                io_srl,
                io_sra,
  output [31:0] io_result
);

  wire [31:0] _io_result_T_3 = io_a + io_b;
  wire [62:0] _io_result_T_27 = {31'h0, io_a} << io_b[4:0];
  wire [31:0] _GEN = {27'h0, io_b[4:0]};
  assign io_result =
    io_add
      ? _io_result_T_3
      : io_lh20
          ? io_b
          : io_sub
              ? io_a - io_b
              : io_slt
                  ? {31'h0, $signed(io_a) < $signed(io_b)}
                  : io_sltu
                      ? {31'h0, io_a < io_b}
                      : io_xor
                          ? io_a ^ io_b
                          : io_or
                              ? io_a | io_b
                              : io_and
                                  ? io_a & io_b
                                  : io_sll
                                      ? _io_result_T_27[31:0]
                                      : io_srl
                                          ? io_a >> _GEN
                                          : io_sra
                                              ? $signed($signed(io_a) >>> _GEN)
                                              : _io_result_T_3;
endmodule

