`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module LSU(
  input         clock,
                reset,
  input  [31:0] io_exuResult,
  input  [2:0]  io_funct3,
  input  [31:0] io_gprRs2Data,
  input         io_load,
                io_store,
  output        io_cacheReq,
                io_cacheWrite,
  output [31:0] io_cacheAddr,
                io_cacheWData,
  output [3:0]  io_cacheWStrb,
  input         io_cacheRespValid,
  input  [31:0] io_cacheRespData,
  output [31:0] io_loadData,
  output        io_busy,
                io_loadDone
);

  reg  [1:0]       state;
  wire             response = state == 2'h2 & io_cacheRespValid;
  reg  [31:0]      addrReg;
  reg  [2:0]       funct3Reg;
  reg  [31:0]      wdataReg;
  reg              writeReg;
  reg  [31:0]      loadDataReg;
  wire [3:0][7:0]  _GEN =
    {{io_cacheRespData[31:24]},
     {io_cacheRespData[23:16]},
     {io_cacheRespData[15:8]},
     {io_cacheRespData[7:0]}};
  wire [7:0]       selectedByte = _GEN[addrReg[1:0]];
  wire [15:0]      selectedHalfword =
    addrReg[1] ? io_cacheRespData[31:16] : io_cacheRespData[15:0];
  wire [7:0][31:0] _GEN_0 =
    {{32'h0},
     {32'h0},
     {{16'h0, selectedHalfword}},
     {{24'h0, selectedByte}},
     {32'h0},
     {io_cacheRespData},
     {{{16{selectedHalfword[15]}}, selectedHalfword}},
     {{{24{selectedByte[7]}}, selectedByte}}};
  wire [31:0]      loadValue = _GEN_0[funct3Reg];
  wire [6:0]       _io_cacheWStrb_T =
    {3'h0,
     funct3Reg == 3'h2 ? 4'hF : funct3Reg == 3'h1 ? 4'h3 : {3'h0, funct3Reg == 3'h0}}
    << addrReg[1:0];
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      addrReg <= 32'h0;
      funct3Reg <= 3'h0;
      wdataReg <= 32'h0;
      writeReg <= 1'h0;
      loadDataReg <= 32'h0;
    end
    else begin
      automatic logic start;
      start = ~(|state) & (io_load | io_store);
      if (state == 2'h2)
        state <= {~response, 1'h0};
      else if (state == 2'h1)
        state <= 2'h2;
      else
        state <= {1'h0, ~(|state) & start};
      if (start) begin
        addrReg <= io_exuResult;
        funct3Reg <= io_funct3;
        wdataReg <= io_gprRs2Data;
        writeReg <= io_store;
      end
      if (response & ~writeReg)
        loadDataReg <= loadValue;
    end
  end // always @(posedge)
  assign io_cacheReq = state == 2'h1;
  assign io_cacheWrite = writeReg;
  assign io_cacheAddr = addrReg;
  assign io_cacheWData = wdataReg;
  assign io_cacheWStrb = _io_cacheWStrb_T[3:0];
  assign io_loadData = response & ~writeReg ? loadValue : loadDataReg;
  assign io_busy = |state;
  assign io_loadDone = response & ~writeReg;
endmodule

