`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module LSU(
  input  [31:0] io_exu_result,
  input  [2:0]  io_funct3,
                io_load_funct3,
  input  [31:0] io_load_addr,
                io_gpr_rs2data,
  output [31:0] io_lsu_addr,
                io_lsu_wdata,
  output [7:0]  io_lsu_wmask,
  output [31:0] io_lsu_loaddata,
  input  [31:0] io_lsu_rdata
);

  wire [3:0][7:0]  _GEN =
    {{io_lsu_rdata[31:24]},
     {io_lsu_rdata[23:16]},
     {io_lsu_rdata[15:8]},
     {io_lsu_rdata[7:0]}};
  wire [7:0]       selectedByte = _GEN[io_load_addr[1:0]];
  wire [15:0]      selectedHalfword =
    io_load_addr[1] ? io_lsu_rdata[31:16] : io_lsu_rdata[15:0];
  wire [7:0][31:0] _GEN_0 =
    {{32'h0},
     {32'h0},
     {{16'h0, selectedHalfword}},
     {{24'h0, selectedByte}},
     {32'h0},
     {io_lsu_rdata},
     {{{16{selectedHalfword[15]}}, selectedHalfword}},
     {{{24{selectedByte[7]}}, selectedByte}}};
  wire [6:0]       _writeMask_T = 7'h1 << io_exu_result[1:0];
  assign io_lsu_addr = io_exu_result;
  assign io_lsu_wdata = io_gpr_rs2data;
  assign io_lsu_wmask =
    {4'h0,
     io_funct3 == 3'h0
       ? _writeMask_T[3:0]
       : io_funct3 == 3'h1
           ? (io_exu_result[0] ? 4'h0 : io_exu_result[1] ? 4'hC : 4'h3)
           : {4{io_funct3 == 3'h2 & io_exu_result[1:0] == 2'h0}}};
  assign io_lsu_loaddata = _GEN_0[io_load_funct3];
endmodule

