`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module MulDiv(
  input         clock,
                reset,
                io_start,
  input  [2:0]  io_funct3,
  input  [31:0] io_a,
                io_b,
  output        io_busy,
                io_done,
  output [31:0] io_result
);

  reg        running;
  reg [5:0]  remainingCycles;
  reg        donePulse;
  reg [31:0] resultReg;
  always @(posedge clock) begin
    if (reset) begin
      running <= 1'h0;
      remainingCycles <= 6'h0;
      donePulse <= 1'h0;
      resultReg <= 32'h0;
    end
    else begin
      automatic logic _GEN;
      _GEN = remainingCycles == 6'h1;
      if (running) begin
        running <= ~_GEN & running;
        if (_GEN)
          remainingCycles <= 6'h0;
        else
          remainingCycles <= remainingCycles - 6'h1;
      end
      else begin
        running <= io_start | running;
        if (io_start)
          remainingCycles <= 6'h20;
      end
      donePulse <= running & _GEN;
      if (~running & io_start) begin
        automatic logic [63:0]      _GEN_0 = {{32{io_a[31]}}, io_a};
        automatic logic [63:0]      _signedProduct_T = _GEN_0 * {{32{io_b[31]}}, io_b};
        automatic logic [63:0]      _GEN_1 = {32'h0, io_b};
        automatic logic [31:0]      aMagnitude = io_a[31] ? ~io_a + 32'h1 : io_a;
        automatic logic [31:0]      bMagnitude = io_b[31] ? ~io_b + 32'h1 : io_b;
        automatic logic [31:0]      signedQuotientMagnitude = aMagnitude / bMagnitude;
        automatic logic [31:0]      signedRemainderMagnitude = aMagnitude % bMagnitude;
        automatic logic             signedOverflow = io_a == 32'h80000000 & (&io_b);
        automatic logic             divideByZero = io_b == 32'h0;
        automatic logic [63:0]      unsignedProduct = {32'h0, io_a} * _GEN_1;
        automatic logic [63:0]      _signedUnsignedProduct_T_2 = _GEN_0 * _GEN_1;
        automatic logic [7:0][31:0] _GEN_2 =
          {{divideByZero ? io_a : io_a % io_b},
           {divideByZero
              ? io_a
              : signedOverflow
                  ? 32'h0
                  : io_a[31]
                      ? ~signedRemainderMagnitude + 32'h1
                      : signedRemainderMagnitude},
           {divideByZero ? 32'hFFFFFFFF : io_a / io_b},
           {divideByZero
              ? 32'hFFFFFFFF
              : signedOverflow
                  ? io_a
                  : io_a[31] ^ io_b[31]
                      ? ~signedQuotientMagnitude + 32'h1
                      : signedQuotientMagnitude},
           {unsignedProduct[63:32]},
           {_signedUnsignedProduct_T_2[63:32]},
           {_signedProduct_T[63:32]},
           {_signedProduct_T[31:0]}};
        resultReg <= _GEN_2[io_funct3];
      end
    end
  end // always @(posedge)
  assign io_busy = running;
  assign io_done = donePulse;
  assign io_result = resultReg;
endmodule

