`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module WBU(
  input  [31:0] io_exuresult,
                io_mem_rdata,
                io_pc,
  input         io_mem_load,
                io_J,
                io_jalr,
                io_csr,
  input  [31:0] io_csrval,
  output [31:0] io_writeback_data
);

  assign io_writeback_data =
    io_mem_load
      ? io_mem_rdata
      : io_J | io_jalr ? io_pc + 32'h4 : io_csr ? io_csrval : io_exuresult;
endmodule

