`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module AXI_Master(
  input         clock,
                reset,
  input  [31:0] io_icache_axi_ar_araddr,
  input         io_icache_axi_ar_arvalid,
  output        io_icache_axi_ar_arready,
  output [31:0] io_icache_axi_r_rdata,
  output        io_icache_axi_r_rlast,
                io_icache_axi_r_rvalid,
  input         io_icache_axi_r_rready,
  input  [31:0] io_lsu_axi_ar_araddr,
  input  [7:0]  io_lsu_axi_ar_arlen,
  input         io_lsu_axi_ar_arvalid,
  output        io_lsu_axi_ar_arready,
  output [31:0] io_lsu_axi_r_rdata,
  output        io_lsu_axi_r_rlast,
                io_lsu_axi_r_rvalid,
  input         io_lsu_axi_r_rready,
  input  [31:0] io_lsu_axi_aw_awaddr,
  input         io_lsu_axi_aw_awvalid,
  output        io_lsu_axi_aw_awready,
  input  [31:0] io_lsu_axi_w_wdata,
  input  [3:0]  io_lsu_axi_w_wstrb,
  input         io_lsu_axi_w_wvalid,
  output        io_lsu_axi_w_wready,
                io_lsu_axi_b_bvalid,
  input         io_lsu_axi_b_bready,
  output [3:0]  io_pmem_axi_ar_arid,
  output [31:0] io_pmem_axi_ar_araddr,
  output [7:0]  io_pmem_axi_ar_arlen,
  output [2:0]  io_pmem_axi_ar_arprot,
  output        io_pmem_axi_ar_arvalid,
  input         io_pmem_axi_ar_arready,
  input  [31:0] io_pmem_axi_r_rdata,
  input         io_pmem_axi_r_rlast,
                io_pmem_axi_r_rvalid,
  output        io_pmem_axi_r_rready,
  output [31:0] io_pmem_axi_aw_awaddr,
  output        io_pmem_axi_aw_awvalid,
  input         io_pmem_axi_aw_awready,
  output [31:0] io_pmem_axi_w_wdata,
  output [3:0]  io_pmem_axi_w_wstrb,
  output        io_pmem_axi_w_wvalid,
  input         io_pmem_axi_w_wready,
                io_pmem_axi_b_bvalid,
  output        io_pmem_axi_b_bready
);

  reg  [1:0] state;
  reg        owner;
  wire       _io_lsu_axi_ar_arready_T = state == 2'h1;
  wire       io_pmem_axi_ar_arvalid_0 =
    _io_lsu_axi_ar_arready_T & (owner ? io_lsu_axi_ar_arvalid : io_icache_axi_ar_arvalid);
  wire       _io_pmem_axi_r_rready_T = state == 2'h2;
  wire       io_pmem_axi_r_rready_0 =
    _io_pmem_axi_r_rready_T & (owner ? io_lsu_axi_r_rready : io_icache_axi_r_rready);
  always @(posedge clock) begin
    if (reset) begin
      state <= 2'h0;
      owner <= 1'h0;
    end
    else begin
      automatic logic selectICache;
      automatic logic selectLsu;
      selectICache = ~(|state) & io_icache_axi_ar_arvalid;
      selectLsu = ~(|state) & ~io_icache_axi_ar_arvalid & io_lsu_axi_ar_arvalid;
      if (state == 2'h2)
        state <=
          {~(io_pmem_axi_r_rvalid & io_pmem_axi_r_rready_0 & io_pmem_axi_r_rlast), 1'h0};
      else if (state == 2'h1) begin
        if (io_pmem_axi_ar_arvalid_0 & io_pmem_axi_ar_arready)
          state <= 2'h2;
        else
          state <= 2'h1;
      end
      else
        state <= {1'h0, ~(|state) & (selectICache | selectLsu)};
      owner <= ~selectICache & (selectLsu | owner);
    end
  end // always @(posedge)
  assign io_icache_axi_ar_arready =
    _io_lsu_axi_ar_arready_T & ~owner & io_pmem_axi_ar_arready;
  assign io_icache_axi_r_rdata = io_pmem_axi_r_rdata;
  assign io_icache_axi_r_rlast = io_pmem_axi_r_rlast;
  assign io_icache_axi_r_rvalid = _io_pmem_axi_r_rready_T & ~owner & io_pmem_axi_r_rvalid;
  assign io_lsu_axi_ar_arready =
    _io_lsu_axi_ar_arready_T & owner & io_pmem_axi_ar_arready;
  assign io_lsu_axi_r_rdata = io_pmem_axi_r_rdata;
  assign io_lsu_axi_r_rlast = io_pmem_axi_r_rlast;
  assign io_lsu_axi_r_rvalid = _io_pmem_axi_r_rready_T & owner & io_pmem_axi_r_rvalid;
  assign io_lsu_axi_aw_awready = io_pmem_axi_aw_awready;
  assign io_lsu_axi_w_wready = io_pmem_axi_w_wready;
  assign io_lsu_axi_b_bvalid = io_pmem_axi_b_bvalid;
  assign io_pmem_axi_ar_arid = {3'h0, owner};
  assign io_pmem_axi_ar_araddr = owner ? io_lsu_axi_ar_araddr : io_icache_axi_ar_araddr;
  assign io_pmem_axi_ar_arlen = owner ? io_lsu_axi_ar_arlen : 8'h3;
  assign io_pmem_axi_ar_arprot = {~owner, 2'h0};
  assign io_pmem_axi_ar_arvalid = io_pmem_axi_ar_arvalid_0;
  assign io_pmem_axi_r_rready = io_pmem_axi_r_rready_0;
  assign io_pmem_axi_aw_awaddr = io_lsu_axi_aw_awaddr;
  assign io_pmem_axi_aw_awvalid = io_lsu_axi_aw_awvalid;
  assign io_pmem_axi_w_wdata = io_lsu_axi_w_wdata;
  assign io_pmem_axi_w_wstrb = io_lsu_axi_w_wstrb;
  assign io_pmem_axi_w_wvalid = io_lsu_axi_w_wvalid;
  assign io_pmem_axi_b_bready = io_lsu_axi_b_bready;
endmodule

