`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module CSR(
  input         clock,
                reset,
  input  [11:0] io_addr,
  input  [31:0] io_op_val,
  input         io_write,
                io_set,
                io_ecall,
                io_mret,
                io_clear,
  input  [31:0] io_pc,
  input         io_we,
  output [31:0] io_readval
);

  reg [31:0] mcycle;
  reg [31:0] mcycleh;
  reg [31:0] mstatus;
  reg [31:0] mtvec;
  reg [31:0] mcause;
  reg [31:0] mepc;
  always @(posedge clock) begin
    if (reset) begin
      mcycle <= 32'h0;
      mcycleh <= 32'h0;
      mstatus <= 32'h0;
      mtvec <= 32'h0;
      mcause <= 32'h0;
      mepc <= 32'h0;
    end
    else begin
      automatic logic [31:0] _GEN;
      _GEN = {32{~io_clear}} | ~io_op_val;
      mcycle <= mcycle + 32'h1;
      if (&mcycle)
        mcycleh <= mcycleh + 32'h1;
      if (io_ecall) begin
        mstatus <= 32'h1800;
        mcause <= 32'hB;
        mepc <= io_pc;
      end
      else begin
        if (~(io_addr != 12'h300 | ~io_we)) begin
          if (io_write)
            mstatus <= io_op_val;
          else if (io_set)
            mstatus <= mstatus | io_op_val;
          else
            mstatus <= _GEN & mstatus;
        end
        if (~(io_addr != 12'h342 | ~io_we)) begin
          if (io_write)
            mcause <= io_op_val;
          else if (io_set)
            mcause <= mcause | io_op_val;
          else
            mcause <= _GEN & mcause;
        end
        if (~(io_addr != 12'h341 | ~io_we)) begin
          if (io_write)
            mepc <= io_op_val;
          else if (io_set)
            mepc <= mepc | io_op_val;
          else
            mepc <= _GEN & mepc;
        end
      end
      if (~(io_addr != 12'h305 | ~io_we)) begin
        if (io_write)
          mtvec <= io_op_val;
        else if (io_set)
          mtvec <= mtvec | io_op_val;
        else
          mtvec <= _GEN & mtvec;
      end
    end
  end // always @(posedge)
  assign io_readval =
    io_ecall
      ? mtvec
      : io_mret
          ? mepc
          : io_addr == 12'h342
              ? mcause
              : io_addr == 12'h341
                  ? mepc
                  : io_addr == 12'h305
                      ? mtvec
                      : io_addr == 12'h300
                          ? mstatus
                          : io_addr == 12'hF12
                              ? 32'h18CE1A1
                              : io_addr == 12'hF11
                                  ? 32'h79737978
                                  : io_addr == 12'hB01
                                      ? mcycleh
                                      : io_addr == 12'hB00 ? mcycle : 32'h0;
endmodule

