`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module GPR(
  input         clock,
                reset,
  input  [4:0]  io_rs1addr,
                io_rs2addr,
                io_rdaddr,
  output [31:0] io_rs1data,
                io_rs2data,
  input  [31:0] io_rddata,
  input         io_we
);

  reg  [31:0]       registers_0;
  reg  [31:0]       registers_1;
  reg  [31:0]       registers_2;
  reg  [31:0]       registers_3;
  reg  [31:0]       registers_4;
  reg  [31:0]       registers_5;
  reg  [31:0]       registers_6;
  reg  [31:0]       registers_7;
  reg  [31:0]       registers_8;
  reg  [31:0]       registers_9;
  reg  [31:0]       registers_10;
  reg  [31:0]       registers_11;
  reg  [31:0]       registers_12;
  reg  [31:0]       registers_13;
  reg  [31:0]       registers_14;
  reg  [31:0]       registers_15;
  reg  [31:0]       registers_16;
  reg  [31:0]       registers_17;
  reg  [31:0]       registers_18;
  reg  [31:0]       registers_19;
  reg  [31:0]       registers_20;
  reg  [31:0]       registers_21;
  reg  [31:0]       registers_22;
  reg  [31:0]       registers_23;
  reg  [31:0]       registers_24;
  reg  [31:0]       registers_25;
  reg  [31:0]       registers_26;
  reg  [31:0]       registers_27;
  reg  [31:0]       registers_28;
  reg  [31:0]       registers_29;
  reg  [31:0]       registers_30;
  reg  [31:0]       registers_31;
  wire [31:0][31:0] _GEN =
    {{registers_31},
     {registers_30},
     {registers_29},
     {registers_28},
     {registers_27},
     {registers_26},
     {registers_25},
     {registers_24},
     {registers_23},
     {registers_22},
     {registers_21},
     {registers_20},
     {registers_19},
     {registers_18},
     {registers_17},
     {registers_16},
     {registers_15},
     {registers_14},
     {registers_13},
     {registers_12},
     {registers_11},
     {registers_10},
     {registers_9},
     {registers_8},
     {registers_7},
     {registers_6},
     {registers_5},
     {registers_4},
     {registers_3},
     {registers_2},
     {registers_1},
     {registers_0}};
  always @(posedge clock) begin
    if (reset) begin
      registers_0 <= 32'h0;
      registers_1 <= 32'h0;
      registers_2 <= 32'h0;
      registers_3 <= 32'h0;
      registers_4 <= 32'h0;
      registers_5 <= 32'h0;
      registers_6 <= 32'h0;
      registers_7 <= 32'h0;
      registers_8 <= 32'h0;
      registers_9 <= 32'h0;
      registers_10 <= 32'h0;
      registers_11 <= 32'h0;
      registers_12 <= 32'h0;
      registers_13 <= 32'h0;
      registers_14 <= 32'h0;
      registers_15 <= 32'h0;
      registers_16 <= 32'h0;
      registers_17 <= 32'h0;
      registers_18 <= 32'h0;
      registers_19 <= 32'h0;
      registers_20 <= 32'h0;
      registers_21 <= 32'h0;
      registers_22 <= 32'h0;
      registers_23 <= 32'h0;
      registers_24 <= 32'h0;
      registers_25 <= 32'h0;
      registers_26 <= 32'h0;
      registers_27 <= 32'h0;
      registers_28 <= 32'h0;
      registers_29 <= 32'h0;
      registers_30 <= 32'h0;
      registers_31 <= 32'h0;
    end
    else begin
      automatic logic _GEN_0 = io_we & (|io_rdaddr);
      if (_GEN_0 & ~(|io_rdaddr))
        registers_0 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h1)
        registers_1 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h2)
        registers_2 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h3)
        registers_3 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h4)
        registers_4 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h5)
        registers_5 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h6)
        registers_6 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h7)
        registers_7 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h8)
        registers_8 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h9)
        registers_9 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'hA)
        registers_10 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'hB)
        registers_11 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'hC)
        registers_12 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'hD)
        registers_13 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'hE)
        registers_14 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'hF)
        registers_15 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h10)
        registers_16 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h11)
        registers_17 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h12)
        registers_18 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h13)
        registers_19 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h14)
        registers_20 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h15)
        registers_21 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h16)
        registers_22 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h17)
        registers_23 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h18)
        registers_24 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h19)
        registers_25 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h1A)
        registers_26 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h1B)
        registers_27 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h1C)
        registers_28 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h1D)
        registers_29 <= io_rddata;
      if (_GEN_0 & io_rdaddr == 5'h1E)
        registers_30 <= io_rddata;
      if (_GEN_0 & (&io_rdaddr))
        registers_31 <= io_rddata;
    end
  end // always @(posedge)
  assign io_rs1data = _GEN[io_rs1addr];
  assign io_rs2data = _GEN[io_rs2addr];
endmodule

