`timescale 1ns / 1ps

`include "defines.vh"

// Generated by CIRCT firtool-1.62.0
module IFU(
  input         clock,
                reset,
                io_fetch,
                io_jump,
  input  [31:0] io_jumpTarget,
  output [31:0] io_ifu_raddr,
  input  [31:0] io_ifu_rdata,
  output [31:0] io_inst,
                io_pc
);

  reg [31:0] pcReg;
  always @(posedge clock) begin
    if (reset)
      pcReg <= 32'h0;
    else if (io_fetch) begin
      if (io_jump)
        pcReg <= io_jumpTarget;
      else
        pcReg <= pcReg + 32'h4;
    end
  end // always @(posedge)
  assign io_ifu_raddr = pcReg;
  assign io_inst = io_ifu_rdata;
  assign io_pc = pcReg;
endmodule

